### ISSUE TITLE
Short Term Goals

### ISSUE THREAD

**Issue by QiLinXue** [jonah-chen/midi-shark#13]
(1) Execute pre-processing code (by Friday)
(2) Sub-problems (Update by Monday)
(2a) De-noising (Real spectrogram to generated spectrogram) <-- relatively easy
(2b) Generated Spectrogram to Note Graph

**Comment by jonah-chen** [comment]
Closing this as (1) is already complete,
(2) is also complete, but is shown to not be very successful, as expected.
