### ISSUE TITLE
Inefficient use of disk space for `notes_generated`

### ISSUE THREAD

**Issue by jonah-chen** [jonah-chen/midi-shark#15]
I have noticed that the `notes_generated` folder contains `.csv` files of note information (the code that generated these files is in `preprocessing/process_midi::save_midi`). Is this intend to be directly read by a human? Please clarify why if it is. If it is not, it would be more efficient to store these in a binary format like `.npy`.

After this is fixed or clarified, I think I can execute the code to preprocess the full dataset, which should take between 2 and 4 hours.

**Comment by joehattori** [comment]
@jonah-chen @QiLinXue Fixed. Merge the PR if it looks good to you guys
Thanks for pointing out!

**Comment by QiLinXue** [comment]
See #17
