### ISSUE TITLE
Re-constructing the transformer without feeding in the ground truth

### ISSUE THREAD

**Issue by joehattori** [jonah-chen/midi-shark#25]
I'm trying to change the implementation of the transformer model so as not to receive the ground truth as an input.
https://github.com/jonah-chen/midi-shark/blob/transformer-pe/model/transformer.py#L177
In the decoder part, current implementation receives the ground truth (`tgt`) and returns the appropriate shape, but how should I return the correct shape without knowing the shape of the output?

**Comment by jonah-chen** [comment]
I'm not completely sure, but the thing is you **do** know the shape of your output. 

When you are chaining layers, you already know the shape of your next layer. For example, in the `torch.nn.Linear` constructor, it takes in both the input and output shape. You can do something similar and we can input the output shape manually in the constructor also when integrating the transformer into the full model.

I am not sure if this is what you are asking for but this is how I interpreted it. I hope this helps.

**Comment by jonah-chen** [comment]
From some of the PyTorch tutorials I was able to construct this. https://github.com/jonah-chen/midi-shark/blob/002d04b88c27b17d66c89cb1ff7d43a9534cd77e/model/encoder_only_transformer.py

Training this right now, was able to get 55% val F1 after 1 epoch, but **note that this ONLY have the encoder part of the transformer**
